CONTAINER Oc4dopenvdbmesher {
	INCLUDE Obase;
    NAME Oc4dopenvdbmesher;
	GROUP ID_OBJECTPROPERTIES {
        REAL C4DOPENVDB_MESHER_ISO { STEP 0.1; MINSLIDER -10.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
        REAL C4DOPENVDB_MESHER_ADAPT { STEP 0.1; MINSLIDER -10.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
    }
}
