CONTAINER Oc4dopenvdbtopolygons {
	INCLUDE Obase;
    NAME Oc4dopenvdbtopolygons;
	GROUP ID_OBJECTPROPERTIES {
        REAL C4DOPENVDB_TOPOLYGONS_ISO { STEP 0.1; MINSLIDER -10.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
        REAL C4DOPENVDB_TOPOLYGONS_ADAPT { STEP 0.1; MINSLIDER -10.0; MAXSLIDER 10.0; CUSTOMGUI REALSLIDER; }
    }
}
