CONTAINER Oc4dopenvdbcombine {
    INCLUDE Obase;
    NAME Oc4dopenvdbcombine;
    GROUP ID_OBJECTPROPERTIES {
        GROUP {
            LAYOUTGROUP; COLUMNS 2;
            GROUP {
                REAL C4DOPENVDB_COMBINE_MULT_A { DEFAULT 1.0; STEP 1.0; }
            }
            GROUP {
                REAL C4DOPENVDB_COMBINE_MULT_B { DEFAULT 1.0; STEP 1.0; }
            }
        }
        LONG C4DOPENVDB_COMBINE_OP {
            CYCLE {
                C4DOPENVDB_COMBINE_OP_COPY_A;
                C4DOPENVDB_COMBINE_OP_COPY_B;
                C4DOPENVDB_COMBINE_OP_INVERT_A;
                C4DOPENVDB_COMBINE_OP_ADD;
                C4DOPENVDB_COMBINE_OP_SUBTRACT;
                C4DOPENVDB_COMBINE_OP_MULT;
                C4DOPENVDB_COMBINE_OP_DIVIDE;
                C4DOPENVDB_COMBINE_OP_MAX;
                C4DOPENVDB_COMBINE_OP_MIN;
                C4DOPENVDB_COMBINE_OP_NEG_A_X_B;
                C4DOPENVDB_COMBINE_OP_A_PLUS_NEG_A_X_B;
                -1;
                C4DOPENVDB_COMBINE_OP_SDF_UNION;
                C4DOPENVDB_COMBINE_OP_SDF_DIFFERENCE;
                C4DOPENVDB_COMBINE_OP_SDF_INTERSECTION;
                -1;
                C4DOPENVDB_COMBINE_OP_ACT_REPLACE_A_B;
                C4DOPENVDB_COMBINE_OP_ACT_UNION;
                C4DOPENVDB_COMBINE_OP_ACT_DIFFERENCE;
                C4DOPENVDB_COMBINE_OP_ACT_INTERESCTION;
            }
        }
        LONG C4DOPENVDB_COMBINE_RESAMPLE {
            CYCLE {
                C4DOPENVDB_COMBINE_RESAMPLE_NONE;
                C4DOPENVDB_COMBINE_RESAMPLE_B_A;
                C4DOPENVDB_COMBINE_RESAMPLE_A_B;
                C4DOPENVDB_COMBINE_RESAMPLE_HIGH_LOW;
                C4DOPENVDB_COMBINE_RESAMPLE_LOW_HIGH;
            }
        }
        LONG C4DOPENVDB_COMBINE_INTERPOLATION {
            CYCLE {
                C4DOPENVDB_COMBINE_INTERPOLATION_LINEAR;
                C4DOPENVDB_COMBINE_INTERPOLATION_NEAREST;
                C4DOPENVDB_COMBINE_INTERPOLATION_QUADRATIC;
            }
        }
        GROUP C4DOPENVDB_COMBINE_DEACTIVATE_GROUP {
            LAYOUTGROUP; COLUMNS 2;
            GROUP{
                BOOL C4DOPENVDB_COMBINE_DEACTIVATE { DEFAULT 0; }
            }
            GROUP {
                REAL C4DOPENVDB_COMBINE_DEACTIVATE_VALUE { DEFAULT 0.0; STEP 0.1; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 10.0; }
            }
        }
        GROUP C4DOPENVDB_COMBINE_PRUNE_GROUP {
            LAYOUTGROUP; COLUMNS 2;
            GROUP {
                BOOL C4DOPENVDB_COMBINE_PRUNE { DEFAULT 1; }
            }
            GROUP {
                SCALE_H;
                REAL C4DOPENVDB_COMBINE_PRUNE_VALUE { DEFAULT 0.0; STEP 0.1; MIN 0.0; MINSLIDER 0.0; MAXSLIDER 10.0; }
            }
        }
        BOOL C4DOPENVDB_COMBINE_SIGN_FLOOD_FILL { DEFAULT 0; }
    }
}
