CONTAINER Oc4dopenvdbfromparticles {
    INCLUDE Obase;
    NAME Oc4dopenvdbfromparticles;
    GROUP ID_OBJECTPROPERTIES {
        LINK C4DOPENVDB_FROMPARTICLES_TPGROUP {  }
        REAL C4DOPENVDB_FROMPARTICLES_VOXEL_SIZE { UNIT METER; DEFAULT 4.0; STEP 0.1; MIN 0.0; MINEX; }
        REAL C4DOPENVDB_FROMPARTICLES_POINT_RADIUS { UNIT METER; DEFAULT 25.0; STEP 1.0; MIN 0.0; MINEX; }
        REAL C4DOPENVDB_FROMPARTICLES_MIN_RADIUS { DEFAULT 1.5; STEP 1.0; MIN 0.0; MINEX; }
        BOOL C4DOPENVDB_FROMPARTICLES_PRUNE { DEFAULT 1; }
        LONG C4DOPENVDB_FROMPARTICLES_BAND_WIDTH { DEFAULT 3; MIN 1; STEP 1; MINEX; }
        LONG C4DOPENVDB_FROMPARTICLES_SHAPE {
            CYCLE {
                C4DOPENVDB_FROMPARTICLES_SHAPE_SPHERE;
                C4DOPENVDB_FROMPARTICLES_SHAPE_VEL;
            }
        }
        REAL C4DOPENVDB_FROMPARTICLES_VEL_MULT { DEFAULT 1.0; STEP 0.1; }
        REAL C4DOPENVDB_FROMPARTICLES_VEL_SPACE { UNIT METER; DEFAULT 1.0; STEP 0.1; }
    }
}
