CONTAINER Oc4dopenvdbprimitive {
	INCLUDE Obase;
    NAME Oc4dopenvdbprimitive;
	GROUP ID_OBJECTPROPERTIES {
        GROUP C4DOPENVDB_PRIM_SETTINGS_GROUP {
            DEFAULT 1;
            LONG C4DOPENVDB_PRIM_SETTINGS_TYPE {
                CYCLE{
                    C4DOPENVDB_PRIM_SETTINGS_TYPE_SPHERE;
                    C4DOPENVDB_PRIM_SETTINGS_TYPE_CUBE;
                    C4DOPENVDB_PRIM_SETTINGS_TYPE_DODEC;
                    C4DOPENVDB_PRIM_SETTINGS_TYPE_ICOS;
                    C4DOPENVDB_PRIM_SETTINGS_TYPE_OCT;
                    C4DOPENVDB_PRIM_SETTINGS_TYPE_TET;
                }
            }
        }
        GROUP C4DOPENVDB_SPHERE_SETTINGS_GROUP {
            HIDDEN; DEFAULT 1;
            REAL C4DOPENVDB_SPHERE_SETTINGS_RADIUS { UNIT METER; DEFAULT 100.0; STEP 1.0; MIN 0.0; MINEX; }
        }
        GROUP C4DOPENVDB_CUBE_SETTINGS_GROUP {
            HIDDEN; DEFAULT 1;
            REAL C4DOPENVDB_CUBE_SETTINGS_SIZE { UNIT METER; DEFAULT 200.0; STEP 1.0; MIN 0.0; MINEX; }
        }
        GROUP C4DOPENVDB_DODEC_SETTINGS_GROUP {
            HIDDEN; DEFAULT 1;
            REAL C4DOPENVDB_DODEC_SETTINGS_SIZE { UNIT METER; DEFAULT 200.0; STEP 1.0; MIN 0.0; MINEX; }
        }
        GROUP C4DOPENVDB_ICOS_SETTINGS_GROUP {
            HIDDEN; DEFAULT 1;
            REAL C4DOPENVDB_ICOS_SETTINGS_SIZE { UNIT METER; DEFAULT 200.0; STEP 1.0; MIN 0.0; MINEX; }
        }
        GROUP C4DOPENVDB_OCT_SETTINGS_GROUP {
            HIDDEN; DEFAULT 1;
            REAL C4DOPENVDB_OCT_SETTINGS_SIZE { UNIT METER; DEFAULT 200.0; STEP 1.0; MIN 0.0; MINEX; }
        }
        GROUP C4DOPENVDB_TET_SETTINGS_GROUP {
            HIDDEN; DEFAULT 1;
            REAL C4DOPENVDB_TET_SETTINGS_SIZE { UNIT METER; DEFAULT 200.0; STEP 1.0; MIN 0.0; MINEX; }
        }
        GROUP C4DOPENVDB_PRIM_GROUP {
            DEFAULT 1;
            GROUP{
                COLUMNS 2;
                REAL C4DOPENVDB_PRIM_VOXEL_SIZE { UNIT METER; DEFAULT 4.0; STEP 0.1; MIN 0.0; MINEX; }
            }
            LONG C4DOPENVDB_PRIM_VDB_TYPE {
                CYCLE
                {
                    C4DOPENVDB_PRIM_VDB_TYPE_SDF;
                    C4DOPENVDB_PRIM_VDB_TYPE_FOG;
                }
            }
            REAL C4DOPENVDB_PRIM_BAND_RADIUS { DEFAULT 3.0; MIN 2.0; STEP 1.0; MINEX; }
            BOOL C4DOPENVDB_PRIM_FILL_INTERIOR { DEFAULT 0; }
            BOOL C4DOPENVDB_PRIM_UNSIGNED_DISTANCE_FIELD { DEFAULT 0; }
        }
    }
}
