enum
{
	// string table definitions
    IDS_C4DOpenVDBPrimitive,
    IDS_C4DOpenVDBHelp,
    IDS_C4DOpenVDBVisualizer,
    IDS_C4DOpenVDBMesher,
    IDS_C4DOpenVDBCombine,
    IDS_C4DOpenVDBFromPolygons,
    IDS_C4DOpenVDBSmooth,
    IDS_C4DOpenVDBReshape,
    
    C4DOPENVDB_SEPARATOR = 150,
    C4DOPENVDB_SURFACE_COUNT = 1000,
    C4DOPENVDB_VOXEL_COUNT = 1001,
    C4DOPENVDB_GRID_NAME = 1002,
    C4DOPENVDB_GRID_TYPE = 1003,
    C4DOPENVDB_DISPLAY_GROUP = 1004,
    C4DOPENVDB_DISPLAY_SHAPE = 1005,
    C4DOPENVDB_DISPLAY_SHAPE_DOT = 1006,
    C4DOPENVDB_DISPLAY_SHAPE_SQUARE = 1007,
    C4DOPENVDB_DISPLAY_SHAPE_BOX = 1008,
    C4DOPENVDB_DISPLAY_SHAPE_BOX_LINES = 1009,
    C4DOPENVDB_GRID_CLASS_SDF = 1010,
    C4DOPENVDB_GRID_CLASS_FOG = 1011,
    C4DOPENVDB_GRID_CLASS_UNKNOWN = 1012,
    C4DOPENVDB_GRID_TRANS_MISMATCH = 1013,
};

#define C4DOPENVDB_DEFAULT_COLOR 0.75f
#define C4DOPENVDB_DEFAULT_VOXEL_SIZE 4.0f
#define C4DOPENVDB_DEFAULT_BAND_WIDTH 3
